channels:
  - "conda-forge"
  - "nodefaults"
dependencies:
  - "python==3.13"
  - "jupyterlab>=4.4.2"

  # Some cool extensions
  - "jupyterlab-favorites"
  - "jupyter-collaboration>=3,<4"
  - "jupyter-server-proxy"
  - "jupyterlab-myst"
  - "jupyterlab-geojson"
  - "nbdime"

  # Python mainstays
  - "numpy"
  - "matplotlib"
  - "hvplot"
  - "pandas"
  - "scipy"
  - "xarray"

  # geo
  - "gdal"
  - "geopandas"
  - "rasterio"
  - "rioxarray"
  - "shapely"
  - "fiona"
  - "pystac-client"

  # geo viz
  - "jupytergis >=0.9.2"
  - "leafmap"
  - "folium"
  - "cartopy"
  - "geoviews"
  - "maplibre"

  # Publishing
  - "mystmd"
  - "typst"

  # Testing and validation
  - "ruff"
  - "pre-commit"

  # GitHub utilities
  - "gh"
  - "gh-scoped-creds"

  # Infrastructure
  - "jupyter-server-proxy"  # Enable proxying MyST sites built from CLI, accessed at `$PREFIX/proxy/$PORT`

  # Pip-only dependencies... ideally we get these on conda-forge.
  - "pip"
  - pip:
    - "jupyter-myst-build-proxy"  # Automatic build and proxying of MyST sites, triggered by requests to `$PREFIX/myst-build/$PATH_TO_MYST_PROJECT`
