channels:
  - "conda-forge"
  - "nodefaults"
dependencies:
  - "python==3.13"
  - "jupyterlab>=4.4.2"

  # Some cool extensions
  - "jupyterlab-favorites <3.3.0"  # 3.3.0 seems to introduce a bug duplicating headers in Notebook Markdown cells (https://jupyter.zulipchat.com/#narrow/channel/103349-ask-anything/topic/Duplicated.20headings.20in.20Markdown.20cells.3F/with/561263040)
  - "jupyter-collaboration>=3,<4"
  - "jupyter-server-proxy"
  - "jupyterlab-myst"
  - "jupyterlab-geojson"
  - "nbdime"

  # Python mainstays
  - "numpy"
  - "matplotlib"
  - "hvplot"
  - "pandas"
  - "scipy"
  - "xarray"

  # geo
  - "gdal"
  - "geopandas"
  - "rasterio"
  - "rioxarray"
  - "shapely"
  - "fiona"
  - "pystac-client"

  # geo viz
  - "jupytergis >=0.9.2"
  - "leafmap"
  - "folium"
  - "cartopy"
  - "geoviews"
  - "maplibre"

  # Publishing
  - "mystmd >=1.6.6"
  - "typst"
  - "jupyter-myst-build-proxy >=0.5.1"

  # Testing and validation
  - "ruff"
  - "pre-commit"

  # GitHub utilities
  - "gh"
  - "gh-scoped-creds"

  # Infrastructure
  - "jupyter-server-proxy"  # Enable proxying MyST sites built from CLI, accessed at `$PREFIX/proxy/$PORT`
